// src/agents_md.rs — generate AGENTS.md so the AI starts analyzing without
// re-learning the export layout each session.
//
// Recognised by Cursor / Claude Code / Codex. ~1-2KB tokens; pays for itself
// on the first question.

use std::fs;
use std::path::Path;

use anyhow::Result;

use crate::config::ExportMode;

/// Write AGENTS.md into the export directory.
pub fn write_agents_md(out_dir: &Path, mode: ExportMode, func_count: usize) -> Result<()> {
    let path = out_dir.join("AGENTS.md");
    let consolidated = matches!(mode, ExportMode::Consolidated);

    let mut s = String::with_capacity(2048);
    s.push_str("# IDA Export for AI Analysis\n\n");
    s.push_str("> Generated by `inp` (Rust, idalib). AI navigation guide below.\n\n");
    s.push_str("## Export mode\n\n");
    s.push_str(&format!("- **resolved mode**: `{}`\n", mode.as_str()));
    s.push_str(&format!("- **total functions**: {}\n", func_count));
    s.push_str("- legacy = per-function files; consolidated = single decompiled.c\n\n");
    s.push_str("## Directory layout\n\n");
    s.push_str("| path | contents |\n| ---- | -------- |\n");
    s.push_str("| `decompiled.c` | all functions, each with a metadata header (consolidated) |\n");
    s.push_str("| `decompile/` | one `.c` per decompiled function (legacy) |\n");
    s.push_str("| `disassembly/` | one `.asm` per fallback function (legacy) |\n");
    s.push_str("| `function_list.txt` | `addr | name | type | fallback_reason` (consolidated) |\n");
    s.push_str("| `function_index.txt` | full function index (legacy) |\n");
    s.push_str("| `callgraph.txt` | sampled call graph from entries/exports |\n");
    s.push_str("| `strings.txt` | `addr | len | string` (filtered in consolidated) |\n");
    s.push_str("| `exports.txt` / `imports.txt` | entry points / extern names |\n");
    if !consolidated {
        s.push_str("| `memory/` | segment hexdumps (1MB shards) |\n");
    }
    s.push_str("\n## Metadata header (per function)\n\n```\n/*\n * func-name: sub_401000\n * func-address: 0x401000\n * export-type: decompile | disassembly-fallback\n * callers: none   (see callgraph.txt)\n * callees: none   (see callgraph.txt)\n * fallback-reason: ...   (only on fallback)\n */\n```\n\n");
    s.push_str("## Suggested workflow\n\n");
    s.push_str("1. Read `imports.txt` / `exports.txt` / `strings.txt` for the global picture.\n");
    s.push_str("2. Find entry points in `exports.txt` / `callgraph.txt`.\n");
    s.push_str("3. Jump to a function by searching `func-address: 0xADDR` in `decompiled.c`.\n");
    s.push_str("4. Trace calls via `callgraph.txt`.\n");
    if consolidated {
        s.push_str("\n**Consolidated mode**: raw `memory/` is skipped; per-function caller/callee\nwalks are replaced by the sampled `callgraph.txt`.\n");
    }

    fs::write(&path, s)?;
    Ok(())
}
